### ISSUE TITLE
Exceptions not getting logged when 'debug' => false

### ISSUE THREAD

**Issue by electricputty** [BKWLD/codebasehq#12]
Hi there,

We're running version 3.2.3 of bkwld/codebasehq on a Laravel 4.0 application. Everything works great locally and on staging but on production nothing is getting sent to CodeBase. I've run some tests and can see this is because the debug flag on the production env config is set to false. If I update this on staging it also stops sending errors. 

Is there anyway to use get errors sent across to CodeBase while debug is set to false?

Many thanks,
Malcolm

**Comment by weotch** [comment]
Huh, I'm surprised to hear that.  I don't use that `config` in [any of this package](https://github.com/BKWLD/codebasehq/search?utf8=%E2%9C%93&q=debug&type=), so it must be supressing the exceptions upriver from this package.  Also, on our projects that use this package, we do see exceptions on `production`, `debug=false` projects.  

I hook into errors here: https://github.com/BKWLD/codebasehq/blob/master/src/Bkwld/CodebaseHQ/ServiceProvider.php#L62-L71.  My guess is that something else you are running is supressing that `error()` listener from firing.

**Comment by electricputty** [comment]
Thanks for getting back to me. We've looked further and you're right, Laravel 4 doesn't seem to differentiate between error 'reporting' and error 'rendering' - so if you debug flag it set to false errors aren't reported. We're parked this for now and a framework upgrade is overdue.  

Best wishes,
Malcolm
